#include "opcodes.h"

const struct opcode_def opcode_table[] = {
    /* 0x0 */  { "NEG",          OP_NEG_D,        6,  REG_NONE, DIRECT,    neg      },
    /* 0x1 is an invalid exption on the 6809 which normally falls back to NEG,
       using it for the run_cycles() unit test instead. */
    /* 0x1 */  { "NOTIMPL",      0x1,             2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x2 */  { "NOTIMPL",      0x2,             2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x3 */  { "COM",          0x3,             6,  REG_NONE, DIRECT,    com      },
    /* 0x4 */  { "NOTIMPL",      0x4,             2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x5 */  { "NOTIMPL",      0x5,             2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x6 */  { "ROR",          OP_ROR_D,        6,  REG_NONE, DIRECT,    ror      },
    /* 0x7 */  { "ASR",          OP_ASR_D,        6,  REG_NONE, DIRECT,    asr      },
    /* 0x8 */  { "ASL",          OP_ASL_D,        6,  REG_NONE, DIRECT,    asl      },
    /* 0x9 */  { "ROL",          OP_ROL_D,        6,  REG_NONE, DIRECT,    rol      },
    /* 0xA */  { "DEC",          0xA,             6,  REG_NONE, DIRECT,    dec      },
    /* 0xB */  { "NOTIMPL",      0xB,             2,  REG_NONE, INHERENT,  notimpl  },
    /* 0xC */  { "INC",          OP_INC_D,        6,  REG_NONE, DIRECT,    inc      },
    /* 0xD */  { "TST",          OP_TST_D,        6,  REG_NONE, DIRECT,    tst      },
    /* 0xE */  { "JMP",          OP_JMP_D,        3,  REG_NONE, DIRECT,    jmp      },
    /* 0xF */  { "CLR",          OP_CLR_D,        6,  REG_NONE, DIRECT,    clr      },
    /* 0x10 */ { "EXTENDED_X10", OP_EXTENDED_X10, 0,  REG_NONE, INHERENT,  extended },
    /* 0x11 */ { "EXTENDED_X11", OP_EXTENDED_X11, 0,  REG_NONE, INHERENT,  extended },
    /* 0x12 */ { "NOP",          OP_NOP,          2,  REG_NONE, INHERENT,  nop      },
    /* 0x13 */ { "NOTIMPL",      0x13,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x14 */ { "NOTIMPL",      0x14,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x15 */ { "NOTIMPL",      0x15,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x16 */ { "NOTIMPL",      0x16,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x17 */ { "NOTIMPL",      0x17,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x18 */ { "NOTIMPL",      0x18,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x19 */ { "DAA",          OP_DAA,          2,  REG_NONE, INHERENT,  daa      },
    /* 0x1A */ { "ORCC",         OP_ORCC,         3,  REG_CC,   IMMEDIATE, orcc     },
    /* 0x1B */ { "NOTIMPL",      0x1B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x1C */ { "ANDCC",        OP_ANDCC,        3,  REG_NONE, IMMEDIATE, andcc    },
    /* 0x1D */ { "SEX",          OP_SEX,          2,  REG_NONE, INHERENT,  sex      },
    /* 0x1E */ { "EXG",          OP_EXG,          8,  REG_NONE, IMMEDIATE, exg      },
    /* 0x1F */ { "TFR",          OP_TFR,          6,  REG_NONE, IMMEDIATE, tfr      },
    /* 0x20 */ { "NOTIMPL",      0x20,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x21 */ { "NOTIMPL",      0x21,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x22 */ { "BHI",          OP_BHI,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x23 */ { "BLS",          OP_BLS,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x24 */ { "BCC",          OP_BCC,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x25 */ { "BCS",          OP_BCS,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x26 */ { "NOTIMPL",      0x26,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x27 */ { "BEQ",          OP_BEQ,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x28 */ { "NOTIMPL",      0x28,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x29 */ { "NOTIMPL",      0x29,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x2A */ { "NOTIMPL",      0x2A,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x2B */ { "BMI",          OP_BMI,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x2C */ { "BGE",          OP_BGE,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x2D */ { "BLT",          OP_BLT,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x2E */ { "BGT",          OP_BGT,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x2F */ { "BLE",          OP_BLE,          3,  REG_NONE, INHERENT,  branch   },
    /* 0x30 */ { "LEAX",         OP_LEAX_I,       4,  REG_X,    INDEXED,   lea      },
    /* 0x31 */ { "LEAY",         OP_LEAY_I,       4,  REG_Y,    INDEXED,   lea      },
    /* 0x32 */ { "LEAS",         OP_LEAS_I,       4,  REG_S,    INDEXED,   lea      },
    /* 0x33 */ { "LEAU",         OP_LEAU_I,       4,  REG_U,    INDEXED,   lea      },
    /* 0x34 */ { "PSHS",         OP_PSHS,         5,  REG_S,    IMMEDIATE, psh      },
    /* 0x35 */ { "PULS",         OP_PULS,         5,  REG_S,    IMMEDIATE, pul      },
    /* 0x36 */ { "PSHU",         OP_PSHU,         5,  REG_U,    IMMEDIATE, psh      },
    /* 0x37 */ { "PULU",         OP_PULU,         5,  REG_U,    IMMEDIATE, pul      },
    /* 0x38 */ { "NOTIMPL",      0x38,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x39 */ { "NOTIMPL",      0x39,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x3A */ { "ABX",          OP_ABX,          3,  REG_NONE, INHERENT,  abx      },
    /* 0x3B */ { "NOTIMPL",      0x3B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x3C */ { "NOTIMPL",      0x3C,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x3D */ { "MUL",          0x3D,            11, REG_NONE, INHERENT,  mul      },
    /* 0x3E */ { "NOTIMPL",      0x3E,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x3F */ { "NOTIMPL",      0x3F,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x40 */ { "NEGA",         0x40,            2,  REG_A,    INHERENT,  neg      },
    /* 0x41 */ { "NOTIMPL",      0x41,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x42 */ { "NOTIMPL",      0x42,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x43 */ { "COMA",         OP_COMA,         2,  REG_A,    INHERENT,  com      },
    /* 0x44 */ { "LSRA",         0x44,            2,  REG_A,    INHERENT,  lsr      },
    /* 0x45 */ { "NOTIMPL",      0x45,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x46 */ { "NOTIMPL",      0x46,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x47 */ { "ASRA",         OP_ASRA,         2,  REG_A,    INHERENT,  asr      },
    /* 0x48 */ { "ASLA",         OP_ASLA,         2,  REG_A,    INHERENT,  asl      },
    /* 0x49 */ { "ROLA",         OP_ROLA,         2,  REG_A,    INHERENT,  rol      },
    /* 0x4A */ { "DECA",         0x4A,            2,  REG_A,    INHERENT,  dec      },
    /* 0x4B */ { "NOTIMPL",      0x4B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x4C */ { "INCA",         OP_INCA,         2,  REG_A,    INHERENT,  inc      },
    /* 0x4D */ { "TSTA",         OP_TSTA,         2,  REG_A,    INHERENT,  tst      },
    /* 0x4E */ { "NOTIMPL",      0x4E,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x4F */ { "CLRA",         0x4F,            2,  REG_A,    INHERENT,  clr      },
    /* 0x50 */ { "NEGB",         0x50,            2,  REG_B,    INHERENT,  neg      },
    /* 0x51 */ { "NOTIMPL",      0x51,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x52 */ { "NOTIMPL",      0x52,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x53 */ { "COMB",         OP_COMB,         2,  REG_B,    INHERENT,  com      },
    /* 0x54 */ { "LSRB",         0x54,            2,  REG_B,    INHERENT,  lsr      },
    /* 0x55 */ { "NOTIMPL",      0x55,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x56 */ { "NOTIMPL",      0x56,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x57 */ { "ASRB",         OP_ASRB,         2,  REG_B,    INHERENT,  asr      },
    /* 0x58 */ { "ASLB",         OP_ASLB,         2,  REG_B,    INHERENT,  asl      },
    /* 0x59 */ { "ROLB",         OP_ROLB,         2,  REG_B,    INHERENT,  rol      },
    /* 0x5A */ { "DECB",         0x5A,            2,  REG_B,    INHERENT,  dec      },
    /* 0x5B */ { "NOTIMPL",      0x5B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x5C */ { "INCB",         OP_INCB,         2,  REG_B,    INHERENT,  inc      },
    /* 0x5D */ { "TSTB",         OP_TSTB,         2,  REG_B,    INHERENT,  tst      },
    /* 0x5E */ { "NOTIMPL",      0x5E,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x5F */ { "CLRB",         0x5F,            2,  REG_B,    INHERENT,  clr      },
    /* 0x60 */ { "NEG",          OP_NEG_I,        6,  REG_NONE, INDEXED,   neg      },
    /* 0x61 */ { "NOTIMPL",      0x61,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x62 */ { "NOTIMPL",      0x62,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x63 */ { "COM",          OP_COM_I,        6,  REG_NONE, INDEXED,   com      },
    /* 0x64 */ { "LSR",          OP_LSR_I,        6,  REG_NONE, INDEXED,   lsr      },
    /* 0x65 */ { "NOTIMPL",      0x65,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x66 */ { "ROR",          OP_ROR_I,        6,  REG_NONE, INDEXED,   ror      },
    /* 0x67 */ { "ASR",          OP_ASR_I,        6,  REG_NONE, INDEXED,   asr      },
    /* 0x68 */ { "ASL",          OP_ASL_I,        6,  REG_NONE, INDEXED,   asl      },
    /* 0x69 */ { "ROL",          OP_ROL_I,        6,  REG_NONE, INDEXED,   rol      },
    /* 0x6A */ { "DEC",          OP_DEC_I,        6,  REG_NONE, INDEXED,   dec      },
    /* 0x6B */ { "NOTIMPL",      0x6B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x6C */ { "INC",          OP_INC_I,        6,  REG_NONE, INDEXED,   inc      },
    /* 0x6D */ { "TST",          OP_TST_I,        6,  REG_NONE, INDEXED,   tst      },
    /* 0x6E */ { "JMP",          OP_JMP_I,        3,  REG_NONE, INDEXED,   jmp      },
    /* 0x6F */ { "CLR",          OP_CLR_I,        6,  REG_NONE, INDEXED,   clr      },
    /* 0x70 */ { "NEG",          OP_NEG_E,        7,  REG_NONE, EXTENDED,  neg      },
    /* 0x71 */ { "NOTIMPL",      0x71,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x72 */ { "NOTIMPL",      0x72,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x73 */ { "COM",          OP_COM_E,        7,  REG_NONE, EXTENDED,  com      },
    /* 0x74 */ { "NOTIMPL",      0x74,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x75 */ { "NOTIMPL",      0x75,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x76 */ { "ROR",          OP_ROR_E,        7,  REG_NONE, EXTENDED,  ror      },
    /* 0x77 */ { "ASR",          OP_ASR_E,        7,  REG_NONE, EXTENDED,  asr      },
    /* 0x78 */ { "ASL",          OP_ASL_E,        7,  REG_NONE, EXTENDED,  asl      },
    /* 0x79 */ { "ROL",          OP_ROL_E,        7,  REG_NONE, EXTENDED,  rol      },
    /* 0x7A */ { "DEC",          OP_DEC_E,        7,  REG_NONE, EXTENDED,  dec      },
    /* 0x7B */ { "NOTIMPL",      0x7B,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x7C */ { "INC",          OP_INC_E,        7,  REG_NONE, EXTENDED,  inc      },
    /* 0x7D */ { "TST",          OP_TST_E,        7,  REG_NONE, EXTENDED,  tst      },
    /* 0x7E */ { "JMP",          OP_JMP_E,        4,  REG_NONE, EXTENDED,  jmp      },
    /* 0x7F */ { "CLR",          OP_CLR_E,        7,  REG_NONE, EXTENDED,  clr      },
    /* 0x80 */ { "SUBA",         OP_SUBA,         2,  REG_A,    IMMEDIATE, sub      },
    /* 0x81 */ { "CMPA",         OP_CMPA,         2,  REG_A,    IMMEDIATE, cmp      },
    /* 0x82 */ { "SBCA",         OP_SBCA,         2,  REG_A,    IMMEDIATE, sbc      },
    /* 0x83 */ { "SUBD",         OP_SUBD,         4,  REG_D,    IMMEDIATE, sub16    },
    /* 0x84 */ { "ANDA",         OP_ANDA,         2,  REG_A,    IMMEDIATE, and      },
    /* 0x85 */ { "BITA",         OP_BITA,         2,  REG_A,    IMMEDIATE, bit      },
    /* 0x86 */ { "LDA",          OP_LDA,          2,  REG_A,    IMMEDIATE, ld       },
    /* 0x87 */ { "NOTIMPL",      0x87,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x88 */ { "EORA",         OP_EORA,         2,  REG_A,    IMMEDIATE, eor      },
    /* 0x89 */ { "ADCA",         OP_ADCA,         2,  REG_A,    IMMEDIATE, adc      },
    /* 0x8A */ { "ORA",          OP_ORA,          2,  REG_A,    IMMEDIATE, or       },
    /* 0x8B */ { "ADDA",         OP_ADDA,         2,  REG_A,    IMMEDIATE, add      },
    /* 0x8C */ { "CMPX",         OP_CMPX,         4,  REG_X,    IMMEDIATE, cmp16    },
    /* 0x8D */ { "NOTIMPL",      0x8D,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x8E */ { "LDX",          OP_LDX,          3,  REG_X,    IMMEDIATE, ld16     },
    /* 0x8F */ { "NOTIMPL",      0x8F,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0x90 */ { "SUBA",         OP_SUBA_D,       4,  REG_A,    DIRECT,    sub      },
    /* 0x91 */ { "CMPA",         OP_CMPA_D,       4,  REG_A,    DIRECT,    cmp      },
    /* 0x92 */ { "SBCA",         OP_SBCA_D,       4,  REG_A,    DIRECT,    sbc      },
    /* 0x93 */ { "SUBD",         OP_SUBD_D,       6,  REG_D,    DIRECT,    sub16    },
    /* 0x94 */ { "ANDA",         OP_ANDA_D,       4,  REG_A,    DIRECT,    and      },
    /* 0x95 */ { "BITA",         OP_BITA_D,       4,  REG_A,    DIRECT,    bit      },
    /* 0x96 */ { "LDA",          OP_LDA_D,        4,  REG_A,    DIRECT,    ld       },
    /* 0x97 */ { "STA",          OP_STA_D,        4,  REG_A,    DIRECT,    st       },
    /* 0x98 */ { "EORA",         OP_EORA_D,       4,  REG_A,    DIRECT,    eor      },
    /* 0x99 */ { "ADCA",         OP_ADCA_D,       4,  REG_A,    DIRECT,    adc      },
    /* 0x9A */ { "ORA",          OP_ORA_D,        4,  REG_A,    DIRECT,    or       },
    /* 0x9B */ { "ADDA",         OP_ADDA_D,       4,  REG_A,    DIRECT,    add      },
    /* 0x9C */ { "CMPX",         OP_CMPX_D,       6,  REG_X,    DIRECT,    cmp16    },
    /* 0x9D */ { "JSR",          OP_JSR_D,        7,  REG_NONE, DIRECT,    jsr      },
    /* 0x9E */ { "LDX",          OP_LDX_D,        5,  REG_X,    DIRECT,    ld16     },
    /* 0x9F */ { "STX",          OP_STX_D,        5,  REG_X,    DIRECT,    st16     },
    /* 0xA0 */ { "SUBA",         OP_SUBA_I,       4,  REG_A,    INDEXED,   sub      },
    /* 0xA1 */ { "CMPA",         OP_CMPA_I,       4,  REG_A,    INDEXED,   cmp      },
    /* 0xA2 */ { "SBCA",         OP_SBCA_I,       4,  REG_A,    INDEXED,   sbc      },
    /* 0xA3 */ { "SUBD",         OP_SUBD_I,       6,  REG_D,    INDEXED,   sub16    },
    /* 0xA4 */ { "ANDA",         OP_ANDA_I,       4,  REG_A,    INDEXED,   and      },
    /* 0xA5 */ { "BITA",         OP_BITA_I,       4,  REG_A,    INDEXED,   bit      },
    /* 0xA6 */ { "LDA",          OP_LDA_I,        4,  REG_A,    INDEXED,   ld       },
    /* 0xA7 */ { "STA",          OP_STA_I,        4,  REG_A,    INDEXED,   st       },
    /* 0xA8 */ { "EORA",         OP_EORA_I,       4,  REG_A,    INDEXED,   eor      },
    /* 0xA9 */ { "ADCA",         OP_ADCA_I,       4,  REG_A,    INDEXED,   adc      },
    /* 0xAA */ { "ORA",          OP_ORA_I,        4,  REG_A,    INDEXED,   or       },
    /* 0xAB */ { "ADDA",         OP_ADDA_I,       4,  REG_A,    INDEXED,   add      },
    /* 0xAC */ { "CMPX",         OP_CMPX_I,       6,  REG_X,    INDEXED,   cmp16    },
    /* 0xAD */ { "JSR",          OP_JSR_I,        7,  REG_NONE, INDEXED,   jsr      },
    /* 0xAE */ { "LDX",          OP_LDX_I,        5,  REG_X,    INDEXED,   ld16     },
    /* 0xAF */ { "STX",          OP_STX_I,        5,  REG_X,    INDEXED,   st16     },
    /* 0xB0 */ { "SUBA",         OP_SUBA_E,       5,  REG_A,    EXTENDED,  sub      },
    /* 0xB1 */ { "CMPA",         OP_CMPA_E,       5,  REG_A,    EXTENDED,  cmp      },
    /* 0xB2 */ { "SBCA",         OP_SBCA_E,       5,  REG_A,    EXTENDED,  sbc      },
    /* 0xB3 */ { "SUBD",         OP_SUBD_E,       7,  REG_D,    EXTENDED,  sub16    },
    /* 0xB4 */ { "ANDA",         OP_ANDA_E,       5,  REG_A,    EXTENDED,  and      },
    /* 0xB5 */ { "BITA",         OP_BITA_E,       5,  REG_A,    EXTENDED,  bit      },
    /* 0xB6 */ { "LDA",          OP_LDA_E,        5,  REG_A,    EXTENDED,  ld       },
    /* 0xB7 */ { "STA",          OP_STA_E,        5,  REG_A,    EXTENDED,  st       },
    /* 0xB8 */ { "EORA",         OP_EORA_E,       5,  REG_A,    EXTENDED,  eor      },
    /* 0xB9 */ { "ADCA",         OP_ADCA_E,       5,  REG_A,    EXTENDED,  adc      },
    /* 0xBA */ { "ORA",          OP_ORA_E,        5,  REG_A,    EXTENDED,  or       },
    /* 0xBB */ { "ADDA",         OP_ADDA_E,       5,  REG_A,    EXTENDED,  add      },
    /* 0xBC */ { "CMPX",         OP_CMPX_E,       7,  REG_X,    EXTENDED,  cmp16    },
    /* 0xBD */ { "JSR",          OP_JSR_E,        8,  REG_NONE, EXTENDED,  jsr      },
    /* 0xBE */ { "LDX",          OP_LDX_E,        6,  REG_X,    EXTENDED,  ld16     },
    /* 0xBF */ { "STX",          OP_STX_E,        6,  REG_X,    EXTENDED,  st16     },
    /* 0xC0 */ { "SUBB",         OP_SUBB,         2,  REG_B,    IMMEDIATE, sub      },
    /* 0xC1 */ { "CMPB",         OP_CMPB,         2,  REG_B,    IMMEDIATE, cmp      },
    /* 0xC2 */ { "SBCB",         OP_SBCB,         2,  REG_B,    IMMEDIATE, sbc      },
    /* 0xC3 */ { "ADDD",         OP_ADDD,         4,  REG_D,    IMMEDIATE, addd     },
    /* 0xC4 */ { "ANDB",         OP_ANDB,         2,  REG_B,    IMMEDIATE, and      },
    /* 0xC5 */ { "BITB",         OP_BITB,         2,  REG_B,    IMMEDIATE, bit      },
    /* 0xC6 */ { "LDB",          OP_LDB,          2,  REG_B,    IMMEDIATE, ld       },
    /* 0xC7 */ { "NOTIMPL",      0xC7,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0xC8 */ { "EORB",         OP_EORB,         2,  REG_B,    IMMEDIATE, eor      },
    /* 0xC9 */ { "ADCB",         OP_ADCB,         2,  REG_B,    IMMEDIATE, adc      },
    /* 0xCA */ { "ORB",          OP_ORB,          2,  REG_B,    IMMEDIATE, or       },
    /* 0xCB */ { "ADDB",         OP_ADDB,         2,  REG_B,    IMMEDIATE, add      },
    /* 0xCC */ { "LDD",          OP_LDD,          3,  REG_D,    IMMEDIATE, ld16     },
    /* 0xCD */ { "NOTIMPL",      0xCD,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0xCE */ { "LDU",          OP_LDU,          3,  REG_U,    IMMEDIATE, ld16     },
    /* 0xCF */ { "NOTIMPL",      0xCF,            2,  REG_NONE, INHERENT,  notimpl  },
    /* 0xD0 */ { "SUBB",         OP_SUBB_D,       4,  REG_B,    DIRECT,    sub      },
    /* 0xD1 */ { "CMPB",         OP_CMPB_D,       4,  REG_B,    DIRECT,    cmp      },
    /* 0xD2 */ { "SBCB",         OP_SBCB_D,       4,  REG_B,    DIRECT,    sbc      },
    /* 0xD3 */ { "ADDD",         OP_ADDD_D,       6,  REG_D,    DIRECT,    addd     },
    /* 0xD4 */ { "ANDB",         OP_ANDB_D,       4,  REG_B,    DIRECT,    and      },
    /* 0xD5 */ { "BITB",         OP_BITB_D,       4,  REG_B,    DIRECT,    bit      },
    /* 0xD6 */ { "LDB",          OP_LDB_D,        4,  REG_B,    DIRECT,    ld       },
    /* 0xD7 */ { "STB",          OP_STB_D,        4,  REG_B,    DIRECT,    st       },
    /* 0xD8 */ { "EORB",         OP_EORB_D,       4,  REG_B,    DIRECT,    eor      },
    /* 0xD9 */ { "ADCB",         OP_ADCB_D,       4,  REG_B,    DIRECT,    adc      },
    /* 0xDA */ { "ORB",          OP_ORB_D,        4,  REG_B,    DIRECT,    or       },
    /* 0xDB */ { "ADDB",         OP_ADDB_D,       4,  REG_B,    DIRECT,    add      },
    /* 0xDC */ { "LDD",          OP_LDD_D,        5,  REG_D,    DIRECT,    ld16     },
    /* 0xDD */ { "STD",          OP_STD_D,        5,  REG_D,    DIRECT,    st16     },
    /* 0xDE */ { "OP_LDU_D",     OP_LDU_D,        5,  REG_U,    DIRECT,    ld16     },
    /* 0xDF */ { "OP_STU_D",     OP_STU_D,        5,  REG_U,    DIRECT,    st16     },
    /* 0xE0 */ { "SUBB",         OP_SUBB_I,       4,  REG_B,    INDEXED,   sub      },
    /* 0xE1 */ { "CMPB",         OP_CMPB_I,       4,  REG_B,    INDEXED,   cmp      },
    /* 0xE2 */ { "SBCB",         OP_SBCB_I,       4,  REG_B,    INDEXED,   sbc      },
    /* 0xE3 */ { "ADDD",         OP_ADDD_I,       6,  REG_D,    INDEXED,   addd     },
    /* 0xE4 */ { "ANDB",         OP_ANDB_I,       4,  REG_B,    INDEXED,   and      },
    /* 0xE5 */ { "BITB",         OP_BITB_I,       4,  REG_B,    INDEXED,   bit      },
    /* 0xE6 */ { "LDB",          OP_LDB_I,        4,  REG_B,    INDEXED,   ld       },
    /* 0xE7 */ { "STB",          OP_STB_I,        4,  REG_B,    INDEXED,   st       },
    /* 0xE8 */ { "EORB",         OP_EORB_I,       4,  REG_B,    INDEXED,   eor      },
    /* 0xE9 */ { "ADCB",         OP_ADCB_I,       4,  REG_B,    INDEXED,   adc      },
    /* 0xEA */ { "ORB",          OP_ORB_I,        4,  REG_B,    INDEXED,   or       },
    /* 0xEB */ { "ADDB",         OP_ADDB_I,       4,  REG_B,    INDEXED,   add      },
    /* 0xEC */ { "LDD",          OP_LDD_I,        5,  REG_D,    INDEXED,   ld16     },
    /* 0xED */ { "STD",          OP_STD_I,        5,  REG_D,    INDEXED,   st16     },
    /* 0xEE */ { "LDU",          OP_LDU_I,        5,  REG_U,    INDEXED,   ld16     },
    /* 0xEF */ { "STU",          OP_STU_I,        5,  REG_U,    INDEXED,   st16     },
    /* 0xF0 */ { "SUBB",         OP_SUBB_E,       5,  REG_B,    EXTENDED,  sub      },
    /* 0xF1 */ { "CMPB",         OP_CMPB_E,       5,  REG_B,    EXTENDED,  cmp      },
    /* 0xF2 */ { "SBCB",         OP_SBCB_E,       5,  REG_B,    EXTENDED,  sbc      },
    /* 0xF3 */ { "ADDD",         OP_ADDD_E,       7,  REG_D,    EXTENDED,  addd     },
    /* 0xF4 */ { "ANDB",         OP_ANDB_E,       5,  REG_B,    EXTENDED,  and      },
    /* 0xF5 */ { "BITB",         OP_BITB_E,       5,  REG_B,    EXTENDED,  bit      },
    /* 0xF6 */ { "LDB",          OP_LDB_E,        5,  REG_B,    EXTENDED,  ld       },
    /* 0xF7 */ { "STB",          OP_STB_E,        5,  REG_B,    EXTENDED,  st       },
    /* 0xF8 */ { "EORB",         OP_EORB_E,       5,  REG_B,    EXTENDED,  eor      },
    /* 0xF9 */ { "ADCB",         OP_ADCB_E,       5,  REG_B,    EXTENDED,  adc      },
    /* 0xFA */ { "ORB",          OP_ORB_E,        5,  REG_B,    EXTENDED,  or       },
    /* 0xFB */ { "ADDB",         OP_ADDB_E,       5,  REG_B,    EXTENDED,  add      },
    /* 0xFC */ { "LDD",          OP_LDD_E,        6,  REG_D,    EXTENDED,  ld16     },
    /* 0xFD */ { "STD",          OP_STD_E,        6,  REG_D,    EXTENDED,  st16     },
    /* 0xFE */ { "LDU",          OP_LDU_E,        6,  REG_U,    EXTENDED,  ld16     },
    /* 0xFF */ { "STU",          OP_STU_E,        6,  REG_U,    EXTENDED,  st16     }
};

const struct opcode_def opcode_ext_x10_table[] = {
    { "NOTIMPL", 0x0,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x10,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x11,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x12,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x13,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x14,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x15,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x16,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x17,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x18,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x19,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x20,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x21,      2, REG_NONE, INHERENT,  notimpl },
    { "LBHI",    OP_LBHI,   5, REG_NONE, INHERENT,  branch16 },
    { "LBLS",    OP_LBLS,   5, REG_NONE, INHERENT,  branch16 },
    { "LBCC",    OP_LBCC,   5, REG_NONE, INHERENT,  branch16 },
    { "LBCS",    OP_LBCS,   5, REG_NONE, INHERENT,  branch16 },
    { "NOTIMPL", 0x26,      2, REG_NONE, INHERENT,  notimpl },
    { "LBEQ",    OP_LBEQ,   5, REG_NONE, INHERENT,  branch16 },
    { "NOTIMPL", 0x28,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x29,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2B,      2, REG_NONE, INHERENT,  notimpl },
    { "LBGE",    OP_LBGE,   5, REG_NONE, INHERENT,  branch16 },
    { "LBLT",    OP_LBLT,   5, REG_NONE, INHERENT,  branch16 },
    { "LBGT",    OP_LBGT,   5, REG_NONE, INHERENT,  branch16 },
    { "LBLE",    OP_LBLE,   5, REG_NONE, INHERENT,  branch16 },
    { "NOTIMPL", 0x30,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x31,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x32,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x33,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x34,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x35,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x36,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x37,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x38,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x39,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x40,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x41,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x42,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x43,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x44,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x45,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x46,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x47,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x48,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x49,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x50,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x51,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x52,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x53,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x54,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x55,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x56,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x57,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x58,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x59,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x60,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x61,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x62,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x63,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x64,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x65,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x66,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x67,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x68,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x69,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x70,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x71,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x72,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x73,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x74,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x75,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x76,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x77,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x78,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x79,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x80,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x81,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x82,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPD",    OP_CMPD,   5, REG_D,    IMMEDIATE, cmp16   },
    { "NOTIMPL", 0x84,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x85,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x86,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x87,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x88,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x89,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8B,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPY",    OP_CMPY,   5, REG_Y,    IMMEDIATE, cmp16   },
    { "NOTIMPL", 0x8D,      2, REG_NONE, INHERENT,  notimpl },
    { "LDY",     OP_LDY,    4, REG_Y,    IMMEDIATE, ld16    },
    { "NOTIMPL", 0x8F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x90,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x91,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x92,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPD",    OP_CMPD_D, 7, REG_D,    DIRECT,    cmp16   },
    { "NOTIMPL", 0x94,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x95,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x96,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x97,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x98,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x99,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9B,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPY",    OP_CMPY_D, 6, REG_Y,    DIRECT,    cmp16   },
    { "NOTIMPL", 0x9D,      2, REG_NONE, INHERENT,  notimpl },
    { "LDY",     OP_LDY_D,  6, REG_Y,    DIRECT,    ld16    },
    { "STY",     OP_STY_D,  6, REG_Y,    DIRECT,    st16    },
    { "NOTIMPL", 0xA0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA2,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPD",    OP_CMPD_I, 7, REG_D,    INDEXED,   cmp16   },
    { "NOTIMPL", 0xA4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAB,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPY",    OP_CMPY_I, 7, REG_Y,    INDEXED,   cmp16   },
    { "NOTIMPL", 0xAD,      2, REG_NONE, INHERENT,  notimpl },
    { "LDY",     OP_LDY_I,  6, REG_Y,    INDEXED,   ld16    },
    { "STY",     OP_STY_I,  6, REG_Y,    INDEXED,   st16    },
    { "NOTIMPL", 0xB0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB2,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPD",    OP_CMPD_E, 8, REG_D,    EXTENDED,  cmp16   },
    { "NOTIMPL", 0xB4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBB,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPY",    OP_CMPY_E, 8, REG_Y,    EXTENDED,  cmp16   },
    { "NOTIMPL", 0xBD,      2, REG_NONE, INHERENT,  notimpl },
    { "LDY",     OP_LDY_E,  7, REG_Y,    EXTENDED,  ld16    },
    { "STY",     OP_STY_E,  7, REG_Y,    EXTENDED,  st16    },
    { "NOTIMPL", 0xC0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCD,      2, REG_NONE, INHERENT,  notimpl },
    { "LDS",     OP_LDS,    4, REG_S,    IMMEDIATE, ld16    },
    { "NOTIMPL", 0xCF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDD,      2, REG_NONE, INHERENT,  notimpl },
    { "LDS",     OP_LDS_D,  6, REG_S,    DIRECT,    ld16    },
    { "STS",     OP_STS_D,  6, REG_S,    DIRECT,    st16    },
    { "NOTIMPL", 0xE0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xED,      2, REG_NONE, INHERENT,  notimpl },
    { "LDS",     OP_LDS_I,  6, REG_S,    INDEXED,   ld16    },
    { "STS",     OP_STS_I,  6, REG_S,    INDEXED,   st16    },
    { "NOTIMPL", 0xF0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFD,      2, REG_NONE, INHERENT,  notimpl },
    { "LDS",     OP_LDS_E,  7, REG_S,    EXTENDED,  ld16    },
    { "STS",     OP_STS_E,  7, REG_S,    EXTENDED,  st16    }
};

const struct opcode_def opcode_ext_x11_table[] = {
    { "NOTIMPL", 0x0,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF,       2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x10,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x11,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x12,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x13,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x14,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x15,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x16,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x17,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x18,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x19,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x1F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x20,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x21,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x22,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x23,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x24,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x25,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x26,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x27,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x28,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x29,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x2F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x30,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x31,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x32,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x33,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x34,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x35,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x36,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x37,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x38,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x39,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x3F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x40,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x41,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x42,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x43,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x44,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x45,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x46,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x47,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x48,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x49,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x4F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x50,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x51,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x52,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x53,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x54,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x55,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x56,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x57,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x58,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x59,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x5F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x60,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x61,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x62,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x63,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x64,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x65,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x66,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x67,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x68,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x69,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x6F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x70,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x71,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x72,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x73,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x74,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x75,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x76,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x77,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x78,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x79,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7B,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7C,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x7F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x80,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x81,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x82,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPU",    OP_CMPU,   5, REG_U,    IMMEDIATE, cmp16   },
    { "NOTIMPL", 0x84,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x85,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x86,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x87,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x88,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x89,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8B,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPS",    OP_CMPS,   5, REG_S,    IMMEDIATE, cmp16   },
    { "NOTIMPL", 0x8D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x8F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x90,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x91,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x92,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPU",    OP_CMPU_D, 7, REG_U,    DIRECT,    cmp16   },
    { "NOTIMPL", 0x94,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x95,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x96,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x97,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x98,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x99,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9A,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9B,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPS",    OP_CMPS_D, 7, REG_S,    DIRECT,    cmp16   },
    { "NOTIMPL", 0x9D,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9E,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0x9F,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA2,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPU",    OP_CMPU_I, 7, REG_U,    INDEXED,   cmp16   },
    { "NOTIMPL", 0xA4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xA9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAB,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPS",    OP_CMPS_I, 7, REG_S,    INDEXED,   cmp16   },
    { "NOTIMPL", 0xAD,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xAF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB2,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPU",    OP_CMPU_E, 8, REG_U,    EXTENDED,  cmp16   },
    { "NOTIMPL", 0xB4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xB9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBB,      2, REG_NONE, INHERENT,  notimpl },
    { "CMPS",    OP_CMPS_E, 8, REG_S,    EXTENDED,  cmp16   },
    { "NOTIMPL", 0xBD,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xBF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xC9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCD,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xCF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xD9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDD,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xDF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xE9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xED,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xEF,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF0,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF1,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF2,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF3,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF4,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF5,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF6,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF7,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF8,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xF9,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFA,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFB,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFC,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFD,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFE,      2, REG_NONE, INHERENT,  notimpl },
    { "NOTIMPL", 0xFF,      2, REG_NONE, INHERENT,  notimpl }
};
